PICK:
  # This will edit the initial xp amount for pickaxes
  # (Default is 200)
  initial-xp-amount: 200
  # This is the value that adds up per level. For example, the 
  # default is 50, then with each level up, the amount of XP
  # needed to get to the next level would be:
  # initial-xp-amount + [add-xp-amount * the current level]
  additive-xp-amount: 50
SWORD:
  initial-xp-amount: 200
  additive-xp-amount: 50
SHOVEL:
  initial-xp-amount: 200
  additive-xp-amount: 50
AXE:
  initial-xp-amount: 200
  additive-xp-amount: 50